### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by seonghyeona** [seonghyeona/myhabit#1]
- [ ] Add type-check, lint, test, lint-staged
- [ ] Add codecov service
- [ ] Design UI Screens to build
- [ ] Organize what server should do for the client

....and so on
